# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af2188476de7db02585ff906823870c724cdcf84eb3e96219beabe0850285e60040177a18b9e715403b63e7fc4b9261909702a47960369a949a2498eff804f87

test:
  secret_key_base: bc9bf9382d2f29318dc205313f7d421e7fd9e978c018f7d0d99bd69eeb9a33c6d060831107e3f31143145a29a647d557b9ae59f4e33ef9f4f538e213d64c5172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
